[package]
name = "nameless-server"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.31", features = ["serde"] }
clap = { version = "4.4.11", features = ["derive"] }
regex = "1.10.2"
lazy_static = "1.4.0"
